stages:
  ingest_static:
    cmd: python src/ingest_static.py data/raw/static/static_data.csv
    deps:
    - src/ingest_static.py
    params:
    - ingest.csv_url
    outs:
    - data/raw/static
  ingest_api:
    cmd: python src/ingest_api.py data/raw/api/api_data.csv
    deps:
    - src/ingest_api.py
    params:
    - ingest.api_url
    outs:
    - data/raw/api
  validate:
    cmd: python src/validate.py data/raw/api/api_data.csv data/raw/static/static_data.csv data/report/validation_report.json
    deps:
      - src/validate.py
      - data/raw/api
      - data/raw/static
    outs:
      - data/report
  prepare:
    cmd: python src/prepare.py data/raw/api/api_data.csv data/raw/static/static_data.csv data/processed/processed_data.csv
    deps:
      - src/prepare.py
      - data/report
    outs:
      - data/processed
  store:
    cmd: python src/store.py data/processed/api/api_data.csv data/processed/static/static_data.csv
    deps:
      - src/store.py
      - data/processed