ingest:
  api_url: http://127.0.0.1:5000/generate_synthetic_data
  csv_url: https://raw.githubusercontent.com/dsrscientist/DSData/master/Telecom_customer_churn.csv
validate:
prepare:

store:

feature_store:

train: