ingest:
  api_url: http://127.0.0.1:5000/generate_synthetic_data
  csv_url: https://raw.githubusercontent.com/dsrscientist/DSData/master/Telecom_customer_churn.csv
validate:
prepare:
  data_path: data/processed
store:
  server: DESKTOP-1JVEQTF
  username: sa
  password: sa123
  driver: {ODBC Driver 17 for SQL Server}
feature_store:

train: