ingest:
  api_url: http://127.0.0.1:5000/generate_synthetic_data
  csv_url: https://raw.githubusercontent.com/dsrscientist/DSData/master/Telecom_customer_churn.csv
validate:
prepare:
  data_path: data/processed
  visualizations_path: data/visualizations/
store:
  server: LAPTOP-4IUEL4B8
  username: sa
  password: sa123
  driver: ODBC Driver 17 for SQL Server
feature_store:
  server: LAPTOP-4IUEL4B8
  username: sa
  password: sa123
  driver: ODBC Driver 17 for SQL Server
  db_name: TELCO_CHURN_DB
  api_key: CgYupUsvdGRc0duC.gyJlzE0UpNoXC8wPLZq0Se7ojMCS65TfLY3CrTOFEha6Pl2NItNFN5rgwFT4fi5v
train:
  api_key: CgYupUsvdGRc0duC.gyJlzE0UpNoXC8wPLZq0Se7ojMCS65TfLY3CrTOFEha6Pl2NItNFN5rgwFT4fi5v
  model_path: model
