{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c7932b6d-c303-4cbc-a45a-806701a7ef55",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyodbc\n",
    "import os\n",
    "import requests\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
    "import sys\n",
    "from matplotlib.backends.backend_pdf import PdfPages\n",
    "\n",
    "\n",
    "# File paths\n",
    "DATA_PATH = \"opt/airflow/data/raw/\"\n",
    "sys.stdout = open(\"logfile.txt\", \"w\")\n",
    "\n",
    "KAGGLE_CSV_PATH = os.path.join(DATA_PATH, \"kaggle_telco_churn.csv\")\n",
    "SYNTHETIC_CSV_PATH = os.path.join(DATA_PATH, \"synthetic_telco_churn.csv\")\n",
    "\n",
    "KAGGLE_CSV_PATH_PROCESSED = os.path.join(DATA_PATH, \"processed_kaggle_telco_churn.csv\")\n",
    "SYNTHETIC_CSV_PATH_PROCESSED = os.path.join(DATA_PATH, \"processed_synthetic_telco_churn.csv\")\n",
    "\n",
    "def impute_missing_values(df):\n",
    "    \"\"\"\n",
    "    Imputes missing values in a DataFrame:\n",
    "    - Numerical columns: Replaced with mean\n",
    "    - Categorical columns: Replaced with mode (most frequent value)\n",
    "    \"\"\"\n",
    "    for column in df.columns:\n",
    "        if df[column].dtype == \"object\":  # Check if column is categorical\n",
    "            df[column].fillna(df[column].mode()[0], inplace=True)  # Fill with mode\n",
    "        else:\n",
    "            df[column].fillna(df[column].mean(), inplace=True)  # Fill with mean\n",
    "    return df\n",
    "\n",
    "\n",
    "# Function for processing\n",
    "def data_processing(source, destination,c):\n",
    "    print (\"PROCESSING THE FILE \", source)\n",
    "    df = pd.read_csv(source)\n",
    "    \n",
    "    print(df.head(2))\n",
    "    print(\"Shape of the dataset \", df.shape)\n",
    "    print(\"Data types of the columns \", df.dtypes)\n",
    "    print(\"Information of the dataset \", df.info())\n",
    "    \n",
    "    print(\"Converting the datatype of Total Charges field\")\n",
    "    # Convert 'TotalCharges' to numeric (errors='coerce' converts non-numeric to NaN)\n",
    "    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')\n",
    "    print (\"Datatype of Total Charges :\", df['TotalCharges'].dtype)\n",
    "\n",
    "    print(\"Checking for missing values and imputing with mean for numerical fields and mode for categorical fields\")\n",
    "    df = impute_missing_values(df)\n",
    "\n",
    "    print(\"Dropping duplicate rows\")\n",
    "    df = df.drop_duplicates() \n",
    "    \n",
    "    # To see the correlation of the numeric fields\n",
    "    df.corr(numeric_only=True)\n",
    "\n",
    "    # Dropping 'customerID' as it's not needed\n",
    "    print(\"Dropping the customerID field as it is not needed\")\n",
    "    df.drop(columns=['customerID'], inplace=True)\n",
    "\n",
    "    # Creating Features \n",
    "    # Convert tenure into categories\n",
    "    def tenure_category(tenure):\n",
    "        if tenure <= 12:\n",
    "            return \"Short-term\"\n",
    "        elif tenure <= 48:\n",
    "            return \"Medium-term\"\n",
    "        else:\n",
    "            return \"Long-term\"\n",
    "    df['TenureCategory'] = df['tenure'].apply(tenure_category)\n",
    "\n",
    "    # Create interaction feature: Total Spend\n",
    "    print(\"Creating 3 new features : TotalSpend, HasInternet and NumServices\" )\n",
    "    df['TotalSpend'] = df['tenure'] * df['MonthlyCharges']\n",
    "\n",
    "    # Create binary feature: Has Internet\n",
    "    df['HasInternet'] = df['InternetService'].apply(lambda x: 0 if x == \"No\" else 1)\n",
    "\n",
    "    # Count of services opted\n",
    "    df['NumServices'] = df[['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', \n",
    "                         'TechSupport', 'StreamingTV', 'StreamingMovies']].apply(lambda x: sum(x == 'Yes'), axis=1)\n",
    "    print(\"Features created\")\n",
    "    \n",
    "    # Standardize numerical columns\n",
    "    print(\"Standardized numerical columns\") \n",
    "    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'TotalSpend']\n",
    "    scaler = StandardScaler()\n",
    "    df[num_cols] = scaler.fit_transform(df[num_cols])\n",
    "\n",
    "    #Encoding categorical variables\n",
    "    print(\"Encoded categorical variables\")\n",
    "    cat_cols = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',\n",
    "                'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', \n",
    "                'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', \n",
    "                'PaperlessBilling', 'PaymentMethod', 'Churn', 'TenureCategory']\n",
    "\n",
    "    label_encoders = {}\n",
    "    for col in cat_cols:\n",
    "        le = LabelEncoder()\n",
    "        df[col] = le.fit_transform(df[col])\n",
    "        label_encoders[col] = le\n",
    "\n",
    "    print(df.head(2))\n",
    "\n",
    "    print (\"Performing the EDA on the data and saving the plots as jpg\", source)\n",
    "    #Perform EDA\n",
    "    # Plot Churn distribution\n",
    "    \n",
    "    plt.figure(figsize=(6, 4))\n",
    "    sns.countplot(x=df[\"Churn\"], palette=\"viridis\")\n",
    "    plt.title(\"Churn Distribution\")\n",
    "    plt.xlabel(\"Churn (0 = No, 1 = Yes)\")\n",
    "    plt.ylabel(\"Count\")\n",
    "    name=\"churn_distribution_\"+c+\".jpg\"\n",
    "    plt.savefig(name, format=\"jpg\", dpi=300) \n",
    "    plt.close()\n",
    "\n",
    "    # Plot numerical feature distributions\n",
    "    df[num_cols].hist(figsize=(12, 5), bins=30, layout=(1, 4), color='purple', edgecolor='black')\n",
    "    plt.suptitle(\"Distribution of Standardized Numerical Features\")\n",
    "    name=\"distribution_num_features_\"+c+\".jpg\"\n",
    "    plt.savefig(name, format=\"jpg\", dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # Boxplot to detect outliers\n",
    "    plt.figure(figsize=(12, 5))\n",
    "    sns.boxplot(data=df[num_cols], palette=\"coolwarm\")\n",
    "    plt.title(\"Boxplot of Standardized Numerical Features (Outliers Detection)\")\n",
    "    plt.xticks(rotation=45)\n",
    "    name=\"boxplot_\"+c+\".jpg\"\n",
    "    plt.savefig(name, format=\"jpg\", dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    #pdf_pages.close()\n",
    "    \n",
    "    print(\"EDA saved to the pdf file\")\n",
    "    # Save cleaned data\n",
    "    df.to_csv(destination, index=False)\n",
    "    \n",
    "    print(\"Data Preprocessing, EDA and feature engineering Completed and Saved.\")\n",
    "    print(\"\\n\")\n",
    "\n",
    "def saving_to_sql (source_file):\n",
    "    server = 'DESKTOP-1JVEQTF' \n",
    "    username = 'sa'  \n",
    "    password = 'sa123'  \n",
    "    driver = '{ODBC Driver 17 for SQL Server}'  \n",
    "\n",
    "    # Create connection string\n",
    "    conn = pyodbc.connect(f'DRIVER={driver};SERVER={server};DATABASE=master;UID={username};PWD={password}', autocommit = True)\n",
    "\n",
    "    # Create a cursor\n",
    "    cursor = conn.cursor()\n",
    "\n",
    "    db_name = 'TELCO_CHURN_DB';\n",
    "\n",
    "    query = f\"SELECT name FROM sys.databases WHERE name = '{db_name}'\"\n",
    "    cursor.execute(query)\n",
    "    row = cursor.fetchone()\n",
    "    if row:\n",
    "        print(f\"Database '{db_name}' already exists.\")\n",
    "    else:\n",
    "        print(f\"Database '{db_name}' does not exist. Creating now...\")\n",
    "    \n",
    "        # Create the database\n",
    "        cursor.execute(f\"CREATE DATABASE {db_name}\")\n",
    "        conn.commit()\n",
    "        print(f\"Database '{db_name}' created successfully.\")\n",
    "\n",
    "    conn_str = f\"mssql+pyodbc://{username}:{password}@{server}/{db_name}?driver=ODBC+Driver+17+for+SQL+Server\"\n",
    "    engine = create_engine(conn_str)\n",
    "    conn = engine.connect()\n",
    "    print(\"Connected successfully!\")\n",
    "\n",
    "    df = pd.read_csv(source_file)\n",
    "    df[\"tenure\"] = df[\"tenure\"].apply(lambda x: round(x, 5))\n",
    "    df[\"MonthlyCharges\"] = df[\"MonthlyCharges\"].apply(lambda x: round(x, 5))\n",
    "    df[\"TotalCharges\"] = df[\"TotalCharges\"].apply(lambda x: round(x, 5))\n",
    "    df[\"TotalSpend\"] = df[\"TotalSpend\"].apply(lambda x: round(x, 5))\n",
    "    table_name = 'telco_churn_table'\n",
    "    query = f\"SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '{table_name}'\"\n",
    "\n",
    "    cursor.execute(query)\n",
    "    row = cursor.fetchone()\n",
    "\n",
    "    if row:\n",
    "        print(f\"Table '{table_name}' exists. Appending the data\", source_file)\n",
    "        df.to_sql(table_name, con=engine, if_exists=\"append\", index=False)\n",
    "        print(\"Data written to sql server successfully\")    \n",
    "    else:\n",
    "        print(f\"Table '{table_name}' does not exist. Creating Table\")\n",
    "        create_table_query = \"\"\"\n",
    "            CREATE TABLE telco_churn_table (\n",
    "            gender int, SeniorCitizen int, Partner int, Dependents int, tenure float, PhoneService int, MultipleLines int, InternetService int,\n",
    "            OnlineSecurity int, OnlineBackup int, DeviceProtection int, TechSupport int, StreamingTV int, StreamingMovies int, Contract int,\n",
    "            PaperlessBilling int, PaymentMethod int, MonthlyCharges float, TotalCharges float, Churn int, TenureCategory int,\n",
    "            TotalSpend float, HasInternet int, NumServices int\n",
    "            )\n",
    "           \"\"\"\n",
    "        cursor.execute(create_table_query)\n",
    "        #conn.commit()\n",
    "        print (\"Table Created successfully\")\n",
    "        df.to_sql(table_name, con=engine, if_exists=\"append\", index=False)\n",
    "        \n",
    "    cursor.close()\n",
    "    conn.close()\n",
    "\n",
    "def main():\n",
    "    c = \"kaggle\"\n",
    "    data_processing(KAGGLE_CSV_PATH, KAGGLE_CSV_PATH_PROCESSED,c)    \n",
    "    c = \"syntheic\"\n",
    "    data_processing(SYNTHETIC_CSV_PATH, SYNTHETIC_CSV_PATH_PROCESSED,c)\n",
    "    saving_to_sql(KAGGLE_CSV_PATH_PROCESSED)\n",
    "    saving_to_sql(SYNTHETIC_CSV_PATH_PROCESSED)\n",
    "    sys.stdout = sys.__stdout__\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "af618d38-1a1e-4256-bfcc-e2ea7af18393",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "218ba268-c6fc-403b-95a6-56dbcb6121b5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
